name: 'Setup ACME Assembler'
description: 'Installs the latest version of ACME assembler'
runs:
  using: composite
  steps:
    - name: Activate Homebrew
      run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      shell: bash
    - name: Install ACME
      run: brew install acme
      shell: bash
    
