name: 'Setup ACME Assembler'
description: 'Installs the latest version of ACME assembler'
runs:
  using: composite
  steps:
    - name: Install ACME
      run: |
        /home/linuxbrew/.linuxbrew/bin/brew install acme
        echo "/home/linuxbrew/.linuxbrew/Cellar/acme/0.97/bin/" >> $GITHUB_PATH
      shell: bash    
