name: 'Setup ACME Assembler'
description: 'Installs the latest version of ACME assembler'
runs:
  using: composite
  steps:
    - name: Install ACME
      run: /home/linuxbrew/.linuxbrew/bin/brew install acme
      shell: bash
    
